name: wifi_geo_map
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  wifi_scan: ^0.4.0+2
  firebase_core: ^2.22.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.14.0
  firebase_storage: ^11.5.1
  cloud_firestore: ^4.13.1
  provider: ^6.1.1
  get: ^4.6.6
  network_info_plus: ^5.0.3
  permission_handler: ^11.0.1
  http: ^1.1.0
  hexagon: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assests/images/

  fonts:
    - family: JetBrains Mono
      fonts:
        - asset: assests/fonts/ttf/JetBrainsMono-Regular.ttf