// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq4w4ZEng75Xwbqzul-tnO7sOtbxJUEfc',
    appId: '1:997322582036:android:89a26af597ca3ef5cadf01',
    messagingSenderId: '997322582036',
    projectId: 'wifigeomap',
    storageBucket: 'wifigeomap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCodEPGLyf5bkOZirSQ4vuAAdo-SnOk2SY',
    appId: '1:997322582036:ios:19f5482eab4591a9cadf01',
    messagingSenderId: '997322582036',
    projectId: 'wifigeomap',
    storageBucket: 'wifigeomap.appspot.com',
    androidClientId: '997322582036-luak3iuk2p39quehsmjs6835pt9u9m8e.apps.googleusercontent.com',
    iosClientId: '997322582036-lbb4mponuseprg0tcrjv44vlmh3vvn0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.wifiGeoMap',
  );
}
